---
title: "Data Visualization Class Work"
subtitle: "Spring 2020" 
author: "Martha Eichlersmith"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
    highlight: "tango"
    code_folding: "hide"
---
These are the projects and labs completed for Data Visualization (STAT 302) - Spring 2020.

***
**Favorite Labs**  
[Lab 05](#l05-2d-surface-geospatial)  
[Lab 08](#l08-positioning)

# L01 ggplot overview
```{r child='Eichlersmith_Martha_L01.Rmd'}
```


# L02 aesthetics  
```{r child='Eichlersmith_Martha_L02.Rmd'}
```

# L03 categories & geom_smooth 
```{r child='Eichlersmith_Martha_L03.Rmd'}
```

# L04 geom_text & annotation
```{r child='Eichlersmith_Martha_L04.Rmd'}
```

# L05 2d surface & geospatial 
```{r child='Eichlersmith_Martha_L05.Rmd'}
```

# L06 errorsbars & layers
```{r child='Eichlersmith_Martha_L06.Rmd'}
```

# L07 scales, axes, & legends
```{r child='Eichlersmith_Martha_L07.Rmd'}
```

# L08 positioning
```{r child='Eichlersmith_Martha_L08.Rmd'}
```

# L09 themes
```{r child='Eichlersmith_Martha_L09.Rmd'}
```